### PR TITLE
Scratchllnl

### PR DESCRIPTION
**Pull request by mayagokhale**
Includes fixes to points 2, 3, 5, 6 from Zhuanhao.

### CODE REVIEW

**Comment by mayagokhale** [comment]
new git push fixes bug report 7: bug of fields without base. Prev "frac" New "fp##frac".

**Comment by mayagokhale** [comment]
Apparently clang 10 on whatever platform travis is running doesn't have that issue with llvm::setCurrentDebugType generating an error the way I am getting on clang 11 Apple clang version 11.0.0 (clang-1100.0.33.17) on my mac.

**Comment by mayagokhale** [comment]
The strange thing is that earlier on Xlat.cpp compiles without errors and it uses that same ifdef __clang__ that is in PluginAction.h. However the sreg.cpp test fails with the compiler error.

**Comment by rseac** [comment]
@mayagokhale  I can take a look at this, and see if I can make changes to scratchllnl to make it pass the checks.

**Comment by rseac** [comment]
@mayagokhale  I simply added a ```using namespace llvm;```.  I don't know if that will continue passing on osx though ...

**Comment by mayagokhale** [comment]
I checked out master, did a merge into scratchllnla and it compiles fine. Thanks!

**Pull request merged**
